# Generated by Django 3.1.5 on 2021-02-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abraxas_api', '0004_auto_20210207_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='pendiente', max_length=10),
        ),
    ]
