# Generated by Django 3.1.5 on 2021-02-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abraxas_api', '0005_auto_20210207_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timespan',
            field=models.IntegerField(default=0),
        ),
    ]
